apiVersion: skaffold/v1beta15
kind: Config
# build:
#   tagPolicy:
#     sha256: {}
#   artifacts:
#   - context: src
#     image: dotnet-hello-world
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
